### PR TITLE
fix: update responsiveness for higher resolution

### LINKED ISSUE #24: Excessive empty screen space on sides when viewing on higher resolution monitor
**Describe the bug**
Viewing the web page in 2k or higher resolution reveal white spaces on the side. I suspect theres a clamping of the width of the page in the css styling

**To Reproduce**
1. Have a 2k+ resolution monitor
2. Load the page

**Expected behavior**
Page should employ a more responsive design for higher resolution

**Screenshots**
Image

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Zen (Firefox based)
- Version: 1.18.10b

### PR DESCRIPTION
**Pull request by vexCoder**
## Description

This PR resolves a layout issue where viewing the web page on monitors with 2K or higher resolution revealed excessive white space on the sides. The CSS styling has been updated to remove the strict width clamping, ensuring the page employs a fully responsive design that scales appropriately on larger screens.

Fixes #24

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Spun up the local dev server and manually verified the layout in the browser.
- [x] Tested responsiveness across different viewport widths (specifically targeting 2K+ resolutions) to confirm the side white spaces are no longer present.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/layouts/default.vue [hunk 1]
```diff
@@ -6,7 +6,7 @@ import InfoBar from '@/components/layout/InfoBar.vue'
 </script>
 
 <template>
-  <div class="max-w-[1920px] mx-auto bg-white shadow-xl min-h-screen relative">
+  <div class="max-w-fill mx-auto bg-white shadow-xl min-h-screen relative">
```
Comment (jmacj) [inline app/layouts/default.vue]: @vexCoder **suggestion:** use `full` insted of `fill`

**Review by jmacj — CHANGES_REQUESTED** [review]

File: app/layouts/default.vue (hunk 1 above)
Comment (vexCoder) [reply app/layouts/default.vue]: Done

**Review by jmacj — APPROVED** [review]
